In [16]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [17]:
df.loc[:10, 'salary_year_avg': 'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0               NaN              NaN
1               NaN              NaN
2               NaN              NaN
3               NaN              NaN
4               NaN              NaN
5               NaN              NaN
6               NaN              NaN
7               NaN              NaN
8               NaN              NaN
9               NaN              NaN
10              NaN              NaN

### Extrat the median for `salary_year_avg` & `salary_hour_avg`

In [18]:
df['salary_year_avg'].median()

115000.0

In [20]:
df['salary_hour_avg'].median()

45.97999954223633

#### Made a variable for thoes median i.e `median_salary_year` & `median_salary_hour`

In [19]:
median_salary_year = df['salary_year_avg'].median()

In [8]:
median_salary_hour = df['salary_hour_avg'].median()

### Filled thoes missing or null value with the generated median value

In [9]:
df_filled = df

df_filled['salary_year_avg'] =  df_filled['salary_year_avg'].fillna(median_salary_year)  
df_filled['salary_hour_avg'] =  df_filled['salary_hour_avg'].fillna(median_salary_hour)

In [13]:
df_filled.loc[:10,  'salary_year_avg' : 'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

## Here we are learning how to removw duplicates value
***DataFrame.drop_duplicates(subset = None, *, keep = 'first', inplace = False, ignore_index = False)***

In [23]:
df_unique = df_filled

df_unique = df_unique.drop_duplicates()

print('Len of org df:              ', len(df_filled))
print('Len of Drop Duplicates df:  ', len(df_unique))
print('Rows Dropped:               ', len(df_filled)-len(df_unique))

Len of org df:               785741
Len of Drop Duplicates df:   785640
Rows Dropped:                101

In [25]:
df_unique = df_unique.drop_duplicates(subset=['job_title', 'company_name'])

print('Len of org df:              ', len(df_filled))
print('Len of Drop Duplicates df:  ', len(df_unique))
print('Rows Dropped:               ', len(df_filled)-len(df_unique))

Len of org df:               785741
Len of Drop Duplicates df:   508042
Rows Dropped:                277699